package exam8_15.exception;

import java.io.File;

public class ExceptionTest {

	public static void main(String[] args) {
		File f = createFile(args[0]);
		System.out.println(f.getName() + " 파일이 성공적으로 생성되었습니다.");
	}
	
	static File createFile(String fileName) {
		try {
			if(fileName == null || fileName.equals(""))
				throw new Exception("파일이름이 유효하지않습니다.");
		} catch(Exception e) {
			fileName = "제목없음.txt";
		} finally {
			File f = new File(fileName);
			createNewfile(f);
			return f;
		}
	}
	static createNewFile(File f) {
		try {
			f.createNewFile();
		} catch(Exception e) {	}
	}

}
