package exam8.exception;

public class ExceptionTest {

	public static void main(String[] args) {
		int[] array = new int[10];
		
		try {
			array[20] = 5;
		} catch(ArrayIndexOutOfBoundsException e) {
//			e.printStackTrace();
			e.getMessage();
		}
		
	}

}
